### ISSUE TITLE
Crash when adding collection?

### ISSUE THREAD

**Issue by jeffchuber** [amikos-tech/chromadb-chart#8]
Hi! 👋 Love this, thanks for making it. I tried this simple experiment on my computer. I was able to get a heartbeat. When I tried the following however:

```
import chromadb

client = chromadb.HttpClient(host="127.0.0.1", port="55897")

collection = client.create_collection("test")

print(collection.count())
```

It crashes

```
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: null argument to internal routine
/docker_entrypoint.sh: line 6:    13 Aborted                 (core dumped) uvicorn chromadb.app:app --workers 1 --host ${CHROMA_SERVER_HOST} --port ${CHROMA_SERVER_HTTP_PORT} --proxy-headers --log-config ${CHROMA_SERVER_LOG_CONFIG}
```

Just curious if you had run into this! thanks!

**Comment by tazarov** [comment]
@jeffchuber , the issue (as you correctly identified it in your docker_entry) was with hnsw lib which unfortunately is platform dependent. I since re-introduced the install prior to booting the DB and now things seem to be working fine (at least on GH ubuntu, macOS). I will add various platform testing in the integration test matrix to ensure it works for "most" platforms.

Possibly the image can be packaged on various platform to ensure better compatibility.

**Comment by tazarov** [comment]
By the way what arch are you running this on?

**Comment by tazarov** [comment]
@jeffchuber did the latest images solve your issue?

**Comment by jeffchuber** [comment]
@tazarov ill try this afternoon :)

**Comment by tazarov** [comment]
@jeffchuber, closing this as I think this issue no longer occurs after hnsw binary distros
